# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ujo48515\Documents\Virtual Accelerator\ASTRAComparisonRunner\astra_comparison_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1231, 552)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.non_magnet_arguments_layout = QtGui.QGridLayout()
        self.non_magnet_arguments_layout.setObjectName(_fromUtf8("non_magnet_arguments_layout"))
        self.formLayout_7 = QtGui.QFormLayout()
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setHorizontalSpacing(3)
        self.formLayout_7.setVerticalSpacing(30)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.linac1_gradient_label = QtGui.QLabel(self.centralwidget)
        self.linac1_gradient_label.setObjectName(_fromUtf8("linac1_gradient_label"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.linac1_gradient_label)
        self.linac1_gradient_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.linac1_gradient_line_edit.setMouseTracking(False)
        self.linac1_gradient_line_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.linac1_gradient_line_edit.setObjectName(_fromUtf8("linac1_gradient_line_edit"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.linac1_gradient_line_edit)
        self.linac1_phase_label = QtGui.QLabel(self.centralwidget)
        self.linac1_phase_label.setObjectName(_fromUtf8("linac1_phase_label"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.linac1_phase_label)
        self.linac1_phase_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.linac1_phase_line_edit.setMouseTracking(False)
        self.linac1_phase_line_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.linac1_phase_line_edit.setObjectName(_fromUtf8("linac1_phase_line_edit"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.linac1_phase_line_edit)
        self.bucking_coil_and_sol_strength_label = QtGui.QLabel(self.centralwidget)
        self.bucking_coil_and_sol_strength_label.setObjectName(_fromUtf8("bucking_coil_and_sol_strength_label"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.bucking_coil_and_sol_strength_label)
        self.bucking_coil_and_sol_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.bucking_coil_and_sol_strength_line_edit.setMouseTracking(False)
        self.bucking_coil_and_sol_strength_line_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.bucking_coil_and_sol_strength_line_edit.setObjectName(_fromUtf8("bucking_coil_and_sol_strength_line_edit"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.bucking_coil_and_sol_strength_line_edit)
        self.linac1_sol1_strength_label = QtGui.QLabel(self.centralwidget)
        self.linac1_sol1_strength_label.setObjectName(_fromUtf8("linac1_sol1_strength_label"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.LabelRole, self.linac1_sol1_strength_label)
        self.linac1_sol1_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.linac1_sol1_strength_line_edit.setMouseTracking(False)
        self.linac1_sol1_strength_line_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.linac1_sol1_strength_line_edit.setObjectName(_fromUtf8("linac1_sol1_strength_line_edit"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.FieldRole, self.linac1_sol1_strength_line_edit)
        self.linac1_sol2_strength_label = QtGui.QLabel(self.centralwidget)
        self.linac1_sol2_strength_label.setObjectName(_fromUtf8("linac1_sol2_strength_label"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.LabelRole, self.linac1_sol2_strength_label)
        self.linac1_sol2_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.linac1_sol2_strength_line_edit.setMouseTracking(False)
        self.linac1_sol2_strength_line_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.linac1_sol2_strength_line_edit.setObjectName(_fromUtf8("linac1_sol2_strength_line_edit"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.FieldRole, self.linac1_sol2_strength_line_edit)
        self.end_of_line_label = QtGui.QLabel(self.centralwidget)
        self.end_of_line_label.setObjectName(_fromUtf8("end_of_line_label"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.LabelRole, self.end_of_line_label)
        self.end_of_line_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.end_of_line_line_edit.setMouseTracking(False)
        self.end_of_line_line_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.end_of_line_line_edit.setObjectName(_fromUtf8("end_of_line_line_edit"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.FieldRole, self.end_of_line_line_edit)
        self.injector_space_charge_check_box = QtGui.QCheckBox(self.centralwidget)
        self.injector_space_charge_check_box.setMouseTracking(False)
        self.injector_space_charge_check_box.setText(_fromUtf8(""))
        self.injector_space_charge_check_box.setChecked(True)
        self.injector_space_charge_check_box.setObjectName(_fromUtf8("injector_space_charge_check_box"))
        self.formLayout_7.setWidget(6, QtGui.QFormLayout.FieldRole, self.injector_space_charge_check_box)
        self.injector_space_charge_switch_label = QtGui.QLabel(self.centralwidget)
        self.injector_space_charge_switch_label.setObjectName(_fromUtf8("injector_space_charge_switch_label"))
        self.formLayout_7.setWidget(6, QtGui.QFormLayout.LabelRole, self.injector_space_charge_switch_label)
        self.rest_of_line_space_charge_switch_label = QtGui.QLabel(self.centralwidget)
        self.rest_of_line_space_charge_switch_label.setObjectName(_fromUtf8("rest_of_line_space_charge_switch_label"))
        self.formLayout_7.setWidget(7, QtGui.QFormLayout.LabelRole, self.rest_of_line_space_charge_switch_label)
        self.rest_of_line_space_charge_check_box = QtGui.QCheckBox(self.centralwidget)
        self.rest_of_line_space_charge_check_box.setMouseTracking(False)
        self.rest_of_line_space_charge_check_box.setText(_fromUtf8(""))
        self.rest_of_line_space_charge_check_box.setChecked(True)
        self.rest_of_line_space_charge_check_box.setObjectName(_fromUtf8("rest_of_line_space_charge_check_box"))
        self.formLayout_7.setWidget(7, QtGui.QFormLayout.FieldRole, self.rest_of_line_space_charge_check_box)
        self.non_magnet_arguments_layout.addLayout(self.formLayout_7, 0, 1, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setHorizontalSpacing(5)
        self.formLayout.setVerticalSpacing(25)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.astra_run_number_label = QtGui.QLabel(self.centralwidget)
        self.astra_run_number_label.setInputMethodHints(QtCore.Qt.ImhNone)
        self.astra_run_number_label.setObjectName(_fromUtf8("astra_run_number_label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.astra_run_number_label)
        self.astra_run_number_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.astra_run_number_line_edit.setMouseTracking(False)
        self.astra_run_number_line_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.astra_run_number_line_edit.setObjectName(_fromUtf8("astra_run_number_line_edit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.astra_run_number_line_edit)
        self.macro_particle_label_2 = QtGui.QLabel(self.centralwidget)
        self.macro_particle_label_2.setObjectName(_fromUtf8("macro_particle_label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.macro_particle_label_2)
        self.macro_particle_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.macro_particle_line_edit.setMouseTracking(False)
        self.macro_particle_line_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.macro_particle_line_edit.setObjectName(_fromUtf8("macro_particle_line_edit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.macro_particle_line_edit)
        self.laser_pulse_length_label = QtGui.QLabel(self.centralwidget)
        self.laser_pulse_length_label.setObjectName(_fromUtf8("laser_pulse_length_label"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.laser_pulse_length_label)
        self.laser_pulse_length_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.laser_pulse_length_line_edit.setMouseTracking(False)
        self.laser_pulse_length_line_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.laser_pulse_length_line_edit.setObjectName(_fromUtf8("laser_pulse_length_line_edit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.laser_pulse_length_line_edit)
        self.spot_size_label = QtGui.QLabel(self.centralwidget)
        self.spot_size_label.setObjectName(_fromUtf8("spot_size_label"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.spot_size_label)
        self.spot_size_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.spot_size_line_edit.setMouseTracking(False)
        self.spot_size_line_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.spot_size_line_edit.setObjectName(_fromUtf8("spot_size_line_edit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.spot_size_line_edit)
        self.charge_label = QtGui.QLabel(self.centralwidget)
        self.charge_label.setObjectName(_fromUtf8("charge_label"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.charge_label)
        self.charge_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.charge_line_edit.setMouseTracking(False)
        self.charge_line_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.charge_line_edit.setObjectName(_fromUtf8("charge_line_edit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.charge_line_edit)
        self.gun_gradient_label = QtGui.QLabel(self.centralwidget)
        self.gun_gradient_label.setObjectName(_fromUtf8("gun_gradient_label"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.gun_gradient_label)
        self.gun_gradient_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.gun_gradient_line_edit.setMouseTracking(False)
        self.gun_gradient_line_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.gun_gradient_line_edit.setObjectName(_fromUtf8("gun_gradient_line_edit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.gun_gradient_line_edit)
        self.gun_phase_label = QtGui.QLabel(self.centralwidget)
        self.gun_phase_label.setObjectName(_fromUtf8("gun_phase_label"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.gun_phase_label)
        self.gun_phase_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.gun_phase_line_edit.setMouseTracking(False)
        self.gun_phase_line_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.gun_phase_line_edit.setObjectName(_fromUtf8("gun_phase_line_edit"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.gun_phase_line_edit)
        self.non_magnet_arguments_layout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.non_magnet_arguments_layout, 0, 0, 1, 1)
        self.magnet_quad_strength_layout = QtGui.QGridLayout()
        self.magnet_quad_strength_layout.setObjectName(_fromUtf8("magnet_quad_strength_layout"))
        self.s02_quads_layout = QtGui.QFormLayout()
        self.s02_quads_layout.setObjectName(_fromUtf8("s02_quads_layout"))
        self.s02_quad1_strength_label = QtGui.QLabel(self.centralwidget)
        self.s02_quad1_strength_label.setObjectName(_fromUtf8("s02_quad1_strength_label"))
        self.s02_quads_layout.setWidget(0, QtGui.QFormLayout.LabelRole, self.s02_quad1_strength_label)
        self.s02_quad1_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.s02_quad1_strength_line_edit.setMouseTracking(False)
        self.s02_quad1_strength_line_edit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.s02_quad1_strength_line_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.s02_quad1_strength_line_edit.setObjectName(_fromUtf8("s02_quad1_strength_line_edit"))
        self.s02_quads_layout.setWidget(0, QtGui.QFormLayout.FieldRole, self.s02_quad1_strength_line_edit)
        self.s02_quad2_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.s02_quad2_strength_line_edit.setMouseTracking(False)
        self.s02_quad2_strength_line_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.s02_quad2_strength_line_edit.setObjectName(_fromUtf8("s02_quad2_strength_line_edit"))
        self.s02_quads_layout.setWidget(1, QtGui.QFormLayout.FieldRole, self.s02_quad2_strength_line_edit)
        self.s02_quad3_strength_label = QtGui.QLabel(self.centralwidget)
        self.s02_quad3_strength_label.setObjectName(_fromUtf8("s02_quad3_strength_label"))
        self.s02_quads_layout.setWidget(2, QtGui.QFormLayout.LabelRole, self.s02_quad3_strength_label)
        self.s02_quad3_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.s02_quad3_strength_line_edit.setMouseTracking(True)
        self.s02_quad3_strength_line_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.s02_quad3_strength_line_edit.setObjectName(_fromUtf8("s02_quad3_strength_line_edit"))
        self.s02_quads_layout.setWidget(2, QtGui.QFormLayout.FieldRole, self.s02_quad3_strength_line_edit)
        self.s02_quad4_strength_label = QtGui.QLabel(self.centralwidget)
        self.s02_quad4_strength_label.setObjectName(_fromUtf8("s02_quad4_strength_label"))
        self.s02_quads_layout.setWidget(3, QtGui.QFormLayout.LabelRole, self.s02_quad4_strength_label)
        self.s02_quad4_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.s02_quad4_strength_line_edit.setMouseTracking(False)
        self.s02_quad4_strength_line_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.s02_quad4_strength_line_edit.setObjectName(_fromUtf8("s02_quad4_strength_line_edit"))
        self.s02_quads_layout.setWidget(3, QtGui.QFormLayout.FieldRole, self.s02_quad4_strength_line_edit)
        self.s02_quad2_strength_label = QtGui.QLabel(self.centralwidget)
        self.s02_quad2_strength_label.setObjectName(_fromUtf8("s02_quad2_strength_label"))
        self.s02_quads_layout.setWidget(1, QtGui.QFormLayout.LabelRole, self.s02_quad2_strength_label)
        self.magnet_quad_strength_layout.addLayout(self.s02_quads_layout, 1, 0, 1, 1)
        self.vela_quads_layout = QtGui.QFormLayout()
        self.vela_quads_layout.setObjectName(_fromUtf8("vela_quads_layout"))
        self.vela_quad1_strength_label = QtGui.QLabel(self.centralwidget)
        self.vela_quad1_strength_label.setObjectName(_fromUtf8("vela_quad1_strength_label"))
        self.vela_quads_layout.setWidget(0, QtGui.QFormLayout.LabelRole, self.vela_quad1_strength_label)
        self.vela_quad2_strength_label = QtGui.QLabel(self.centralwidget)
        self.vela_quad2_strength_label.setObjectName(_fromUtf8("vela_quad2_strength_label"))
        self.vela_quads_layout.setWidget(1, QtGui.QFormLayout.LabelRole, self.vela_quad2_strength_label)
        self.vela_quad2_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.vela_quad2_strength_line_edit.setMouseTracking(False)
        self.vela_quad2_strength_line_edit.setObjectName(_fromUtf8("vela_quad2_strength_line_edit"))
        self.vela_quads_layout.setWidget(1, QtGui.QFormLayout.FieldRole, self.vela_quad2_strength_line_edit)
        self.vela_quad3_strength_label = QtGui.QLabel(self.centralwidget)
        self.vela_quad3_strength_label.setObjectName(_fromUtf8("vela_quad3_strength_label"))
        self.vela_quads_layout.setWidget(2, QtGui.QFormLayout.LabelRole, self.vela_quad3_strength_label)
        self.vela_quad3_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.vela_quad3_strength_line_edit.setMouseTracking(False)
        self.vela_quad3_strength_line_edit.setObjectName(_fromUtf8("vela_quad3_strength_line_edit"))
        self.vela_quads_layout.setWidget(2, QtGui.QFormLayout.FieldRole, self.vela_quad3_strength_line_edit)
        self.vela_quad4_strength_label = QtGui.QLabel(self.centralwidget)
        self.vela_quad4_strength_label.setObjectName(_fromUtf8("vela_quad4_strength_label"))
        self.vela_quads_layout.setWidget(3, QtGui.QFormLayout.LabelRole, self.vela_quad4_strength_label)
        self.vela_quad4_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.vela_quad4_strength_line_edit.setMouseTracking(False)
        self.vela_quad4_strength_line_edit.setObjectName(_fromUtf8("vela_quad4_strength_line_edit"))
        self.vela_quads_layout.setWidget(3, QtGui.QFormLayout.FieldRole, self.vela_quad4_strength_line_edit)
        self.vela_quad5_strength_label = QtGui.QLabel(self.centralwidget)
        self.vela_quad5_strength_label.setObjectName(_fromUtf8("vela_quad5_strength_label"))
        self.vela_quads_layout.setWidget(4, QtGui.QFormLayout.LabelRole, self.vela_quad5_strength_label)
        self.vela_quad5_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.vela_quad5_strength_line_edit.setMouseTracking(False)
        self.vela_quad5_strength_line_edit.setObjectName(_fromUtf8("vela_quad5_strength_line_edit"))
        self.vela_quads_layout.setWidget(4, QtGui.QFormLayout.FieldRole, self.vela_quad5_strength_line_edit)
        self.vela_quad6_strength_label = QtGui.QLabel(self.centralwidget)
        self.vela_quad6_strength_label.setObjectName(_fromUtf8("vela_quad6_strength_label"))
        self.vela_quads_layout.setWidget(5, QtGui.QFormLayout.LabelRole, self.vela_quad6_strength_label)
        self.vela_quad6_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.vela_quad6_strength_line_edit.setMouseTracking(False)
        self.vela_quad6_strength_line_edit.setObjectName(_fromUtf8("vela_quad6_strength_line_edit"))
        self.vela_quads_layout.setWidget(5, QtGui.QFormLayout.FieldRole, self.vela_quad6_strength_line_edit)
        self.vela_quad1_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.vela_quad1_strength_line_edit.setMouseTracking(False)
        self.vela_quad1_strength_line_edit.setObjectName(_fromUtf8("vela_quad1_strength_line_edit"))
        self.vela_quads_layout.setWidget(0, QtGui.QFormLayout.FieldRole, self.vela_quad1_strength_line_edit)
        self.magnet_quad_strength_layout.addLayout(self.vela_quads_layout, 1, 1, 1, 1)
        self.ba1_quads_layout = QtGui.QFormLayout()
        self.ba1_quads_layout.setObjectName(_fromUtf8("ba1_quads_layout"))
        self.ba1_quad1_strength_label = QtGui.QLabel(self.centralwidget)
        self.ba1_quad1_strength_label.setObjectName(_fromUtf8("ba1_quad1_strength_label"))
        self.ba1_quads_layout.setWidget(0, QtGui.QFormLayout.LabelRole, self.ba1_quad1_strength_label)
        self.ba1_quad1_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.ba1_quad1_strength_line_edit.setMouseTracking(False)
        self.ba1_quad1_strength_line_edit.setObjectName(_fromUtf8("ba1_quad1_strength_line_edit"))
        self.ba1_quads_layout.setWidget(0, QtGui.QFormLayout.FieldRole, self.ba1_quad1_strength_line_edit)
        self.ba1_quad2_strength_label = QtGui.QLabel(self.centralwidget)
        self.ba1_quad2_strength_label.setObjectName(_fromUtf8("ba1_quad2_strength_label"))
        self.ba1_quads_layout.setWidget(1, QtGui.QFormLayout.LabelRole, self.ba1_quad2_strength_label)
        self.ba1_quad2_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.ba1_quad2_strength_line_edit.setMouseTracking(False)
        self.ba1_quad2_strength_line_edit.setObjectName(_fromUtf8("ba1_quad2_strength_line_edit"))
        self.ba1_quads_layout.setWidget(1, QtGui.QFormLayout.FieldRole, self.ba1_quad2_strength_line_edit)
        self.ba1_quad3_strength_label = QtGui.QLabel(self.centralwidget)
        self.ba1_quad3_strength_label.setObjectName(_fromUtf8("ba1_quad3_strength_label"))
        self.ba1_quads_layout.setWidget(2, QtGui.QFormLayout.LabelRole, self.ba1_quad3_strength_label)
        self.ba1_quad3_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.ba1_quad3_strength_line_edit.setMouseTracking(False)
        self.ba1_quad3_strength_line_edit.setObjectName(_fromUtf8("ba1_quad3_strength_line_edit"))
        self.ba1_quads_layout.setWidget(2, QtGui.QFormLayout.FieldRole, self.ba1_quad3_strength_line_edit)
        self.ba1_quad4_strength_label = QtGui.QLabel(self.centralwidget)
        self.ba1_quad4_strength_label.setObjectName(_fromUtf8("ba1_quad4_strength_label"))
        self.ba1_quads_layout.setWidget(3, QtGui.QFormLayout.LabelRole, self.ba1_quad4_strength_label)
        self.ba1_quad4_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.ba1_quad4_strength_line_edit.setMouseTracking(False)
        self.ba1_quad4_strength_line_edit.setObjectName(_fromUtf8("ba1_quad4_strength_line_edit"))
        self.ba1_quads_layout.setWidget(3, QtGui.QFormLayout.FieldRole, self.ba1_quad4_strength_line_edit)
        self.ba1_quad5_strength_label = QtGui.QLabel(self.centralwidget)
        self.ba1_quad5_strength_label.setObjectName(_fromUtf8("ba1_quad5_strength_label"))
        self.ba1_quads_layout.setWidget(4, QtGui.QFormLayout.LabelRole, self.ba1_quad5_strength_label)
        self.ba1_quad5_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.ba1_quad5_strength_line_edit.setMouseTracking(False)
        self.ba1_quad5_strength_line_edit.setObjectName(_fromUtf8("ba1_quad5_strength_line_edit"))
        self.ba1_quads_layout.setWidget(4, QtGui.QFormLayout.FieldRole, self.ba1_quad5_strength_line_edit)
        self.ba1_quad6_strength_label = QtGui.QLabel(self.centralwidget)
        self.ba1_quad6_strength_label.setObjectName(_fromUtf8("ba1_quad6_strength_label"))
        self.ba1_quads_layout.setWidget(5, QtGui.QFormLayout.LabelRole, self.ba1_quad6_strength_label)
        self.ba1_quad6_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.ba1_quad6_strength_line_edit.setMouseTracking(False)
        self.ba1_quad6_strength_line_edit.setObjectName(_fromUtf8("ba1_quad6_strength_line_edit"))
        self.ba1_quads_layout.setWidget(5, QtGui.QFormLayout.FieldRole, self.ba1_quad6_strength_line_edit)
        self.ba1_quad7_strength_label = QtGui.QLabel(self.centralwidget)
        self.ba1_quad7_strength_label.setObjectName(_fromUtf8("ba1_quad7_strength_label"))
        self.ba1_quads_layout.setWidget(6, QtGui.QFormLayout.LabelRole, self.ba1_quad7_strength_label)
        self.ba1_quad7_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.ba1_quad7_strength_line_edit.setMouseTracking(True)
        self.ba1_quad7_strength_line_edit.setObjectName(_fromUtf8("ba1_quad7_strength_line_edit"))
        self.ba1_quads_layout.setWidget(6, QtGui.QFormLayout.FieldRole, self.ba1_quad7_strength_line_edit)
        self.magnet_quad_strength_layout.addLayout(self.ba1_quads_layout, 3, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.magnet_quad_strength_layout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.magnet_quad_strength_layout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.magnet_quad_strength_layout.addWidget(self.label, 0, 0, 1, 1)
        self.c2v_quads_layout = QtGui.QFormLayout()
        self.c2v_quads_layout.setObjectName(_fromUtf8("c2v_quads_layout"))
        self.c2v_quad1_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.c2v_quad1_strength_line_edit.setMouseTracking(False)
        self.c2v_quad1_strength_line_edit.setObjectName(_fromUtf8("c2v_quad1_strength_line_edit"))
        self.c2v_quads_layout.setWidget(0, QtGui.QFormLayout.FieldRole, self.c2v_quad1_strength_line_edit)
        self.c2v_quad2_strength_label = QtGui.QLabel(self.centralwidget)
        self.c2v_quad2_strength_label.setObjectName(_fromUtf8("c2v_quad2_strength_label"))
        self.c2v_quads_layout.setWidget(1, QtGui.QFormLayout.LabelRole, self.c2v_quad2_strength_label)
        self.c2v_quad2_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.c2v_quad2_strength_line_edit.setMouseTracking(False)
        self.c2v_quad2_strength_line_edit.setObjectName(_fromUtf8("c2v_quad2_strength_line_edit"))
        self.c2v_quads_layout.setWidget(1, QtGui.QFormLayout.FieldRole, self.c2v_quad2_strength_line_edit)
        self.c2v_quad3_strength_label = QtGui.QLabel(self.centralwidget)
        self.c2v_quad3_strength_label.setObjectName(_fromUtf8("c2v_quad3_strength_label"))
        self.c2v_quads_layout.setWidget(2, QtGui.QFormLayout.LabelRole, self.c2v_quad3_strength_label)
        self.c2v_quad3_strength_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.c2v_quad3_strength_line_edit.setMouseTracking(False)
        self.c2v_quad3_strength_line_edit.setObjectName(_fromUtf8("c2v_quad3_strength_line_edit"))
        self.c2v_quads_layout.setWidget(2, QtGui.QFormLayout.FieldRole, self.c2v_quad3_strength_line_edit)
        self.c2v_quad1_strength_label = QtGui.QLabel(self.centralwidget)
        self.c2v_quad1_strength_label.setObjectName(_fromUtf8("c2v_quad1_strength_label"))
        self.c2v_quads_layout.setWidget(0, QtGui.QFormLayout.LabelRole, self.c2v_quad1_strength_label)
        self.magnet_quad_strength_layout.addLayout(self.c2v_quads_layout, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.magnet_quad_strength_layout.addWidget(self.label_2, 2, 0, 1, 1)
        self.directory_and_run_button_layout = QtGui.QGridLayout()
        self.directory_and_run_button_layout.setObjectName(_fromUtf8("directory_and_run_button_layout"))
        self.directory_line_edit = QtGui.QLineEdit(self.centralwidget)
        self.directory_line_edit.setMouseTracking(False)
        self.directory_line_edit.setObjectName(_fromUtf8("directory_line_edit"))
        self.directory_and_run_button_layout.addWidget(self.directory_line_edit, 1, 0, 1, 1)
        self.directory_label = QtGui.QLabel(self.centralwidget)
        self.directory_label.setObjectName(_fromUtf8("directory_label"))
        self.directory_and_run_button_layout.addWidget(self.directory_label, 0, 0, 1, 1)
        self.runButton = QtGui.QPushButton(self.centralwidget)
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.directory_and_run_button_layout.addWidget(self.runButton, 1, 1, 1, 1)
        self.magnet_quad_strength_layout.addLayout(self.directory_and_run_button_layout, 4, 0, 1, 2)
        self.gridLayout.addLayout(self.magnet_quad_strength_layout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1231, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_YAML = QtGui.QAction(MainWindow)
        self.actionImport_YAML.setObjectName(_fromUtf8("actionImport_YAML"))
        self.actionExport_YAML = QtGui.QAction(MainWindow)
        self.actionExport_YAML.setObjectName(_fromUtf8("actionExport_YAML"))
        self.menuFile.addAction(self.actionImport_YAML)
        self.menuFile.addAction(self.actionExport_YAML)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ASTRA Run Comparison Tool", None))
        self.linac1_gradient_label.setText(_translate("MainWindow", "Linac 1 Gradient (MV/m)", None))
        self.linac1_gradient_line_edit.setPlaceholderText(_translate("MainWindow", "21", None))
        self.linac1_phase_label.setText(_translate("MainWindow", "Linac 1 Phase (deg.)", None))
        self.linac1_phase_line_edit.setPlaceholderText(_translate("MainWindow", "-16", None))
        self.bucking_coil_and_sol_strength_label.setText(_translate("MainWindow", "Bucking Coil and Sol Strength (A)", None))
        self.bucking_coil_and_sol_strength_line_edit.setPlaceholderText(_translate("MainWindow", "0.345", None))
        self.linac1_sol1_strength_label.setText(_translate("MainWindow", "Linac 1 Solenoid 1 Strength (A)", None))
        self.linac1_sol1_strength_line_edit.setPlaceholderText(_translate("MainWindow", "0.05", None))
        self.linac1_sol2_strength_label.setText(_translate("MainWindow", "Linac 1 Solenoid 2 Strength (A)", None))
        self.linac1_sol2_strength_line_edit.setPlaceholderText(_translate("MainWindow", "-0.05", None))
        self.end_of_line_label.setText(_translate("MainWindow", "End of Line (cm)", None))
        self.end_of_line_line_edit.setPlaceholderText(_translate("MainWindow", "337", None))
        self.injector_space_charge_switch_label.setText(_translate("MainWindow", "Injector Space Charge (On/Off)", None))
        self.rest_of_line_space_charge_switch_label.setText(_translate("MainWindow", "Rest of Line Space Charge (On/Off)", None))
        self.astra_run_number_label.setText(_translate("MainWindow", "Astra Run No.", None))
        self.astra_run_number_line_edit.setPlaceholderText(_translate("MainWindow", "001", None))
        self.macro_particle_label_2.setText(_translate("MainWindow", "No. Macro Particles", None))
        self.macro_particle_line_edit.setPlaceholderText(_translate("MainWindow", "1000", None))
        self.laser_pulse_length_label.setText(_translate("MainWindow", "Laser Pulse Length (ps)", None))
        self.laser_pulse_length_line_edit.setPlaceholderText(_translate("MainWindow", "3", None))
        self.spot_size_label.setText(_translate("MainWindow", "Spot Size (sig in mm)", None))
        self.spot_size_line_edit.setPlaceholderText(_translate("MainWindow", "0.25", None))
        self.charge_label.setText(_translate("MainWindow", "Charge (nC)", None))
        self.charge_line_edit.setPlaceholderText(_translate("MainWindow", "0.25", None))
        self.gun_gradient_label.setText(_translate("MainWindow", "Gun Gradient (MV/m)", None))
        self.gun_gradient_line_edit.setPlaceholderText(_translate("MainWindow", "71.5", None))
        self.gun_phase_label.setText(_translate("MainWindow", "Gun Phase (deg.)", None))
        self.gun_phase_line_edit.setPlaceholderText(_translate("MainWindow", "-9", None))
        self.s02_quad1_strength_label.setText(_translate("MainWindow", "QUAD1 Strength (k)", None))
        self.s02_quad1_strength_line_edit.setPlaceholderText(_translate("MainWindow", "3.012", None))
        self.s02_quad2_strength_line_edit.setPlaceholderText(_translate("MainWindow", "-4.719", None))
        self.s02_quad3_strength_label.setText(_translate("MainWindow", "QUAD3 Strength (k)", None))
        self.s02_quad3_strength_line_edit.setPlaceholderText(_translate("MainWindow", "-4.07", None))
        self.s02_quad4_strength_label.setText(_translate("MainWindow", "QUAD4 Strength (k)", None))
        self.s02_quad4_strength_line_edit.setPlaceholderText(_translate("MainWindow", "13.316", None))
        self.s02_quad2_strength_label.setText(_translate("MainWindow", "QUAD2 Strength (k)", None))
        self.vela_quad1_strength_label.setText(_translate("MainWindow", "QUAD1 Strength (k)", None))
        self.vela_quad2_strength_label.setText(_translate("MainWindow", "QUAD2 Strength (k)", None))
        self.vela_quad2_strength_line_edit.setPlaceholderText(_translate("MainWindow", "-18.492", None))
        self.vela_quad3_strength_label.setText(_translate("MainWindow", "QUAD3 Strength (k)", None))
        self.vela_quad3_strength_line_edit.setPlaceholderText(_translate("MainWindow", "5.267", None))
        self.vela_quad4_strength_label.setText(_translate("MainWindow", "QUAD4 Strength (k)", None))
        self.vela_quad4_strength_line_edit.setPlaceholderText(_translate("MainWindow", "-5.527", None))
        self.vela_quad5_strength_label.setText(_translate("MainWindow", "QUAD5 Strength (k)", None))
        self.vela_quad5_strength_line_edit.setPlaceholderText(_translate("MainWindow", "6.721", None))
        self.vela_quad6_strength_label.setText(_translate("MainWindow", "QUAD6 Strength (k)", None))
        self.vela_quad6_strength_line_edit.setPlaceholderText(_translate("MainWindow", "8.891", None))
        self.vela_quad1_strength_line_edit.setPlaceholderText(_translate("MainWindow", "20.743", None))
        self.ba1_quad1_strength_label.setText(_translate("MainWindow", "QUAD1 Strength (k)", None))
        self.ba1_quad1_strength_line_edit.setPlaceholderText(_translate("MainWindow", "-3.8", None))
        self.ba1_quad2_strength_label.setText(_translate("MainWindow", "QUAD2 Strength (k)", None))
        self.ba1_quad2_strength_line_edit.setPlaceholderText(_translate("MainWindow", "9.9", None))
        self.ba1_quad3_strength_label.setText(_translate("MainWindow", "QUAD3 Strength (k)", None))
        self.ba1_quad3_strength_line_edit.setPlaceholderText(_translate("MainWindow", "-11.5", None))
        self.ba1_quad4_strength_label.setText(_translate("MainWindow", "QUAD4 Strength (k)", None))
        self.ba1_quad4_strength_line_edit.setPlaceholderText(_translate("MainWindow", "5.0", None))
        self.ba1_quad5_strength_label.setText(_translate("MainWindow", "QUAD5 Strength (k)", None))
        self.ba1_quad5_strength_line_edit.setPlaceholderText(_translate("MainWindow", "-3.5", None))
        self.ba1_quad6_strength_label.setText(_translate("MainWindow", "QUAD6 Strength (k)", None))
        self.ba1_quad6_strength_line_edit.setPlaceholderText(_translate("MainWindow", "-3.5", None))
        self.ba1_quad7_strength_label.setText(_translate("MainWindow", "QUAD7 Strength in Dipole (k)", None))
        self.ba1_quad7_strength_line_edit.setPlaceholderText(_translate("MainWindow", "2.5", None))
        self.label_3.setText(_translate("MainWindow", "BA1", None))
        self.label_4.setText(_translate("MainWindow", "VELA", None))
        self.label.setText(_translate("MainWindow", "S02", None))
        self.c2v_quad1_strength_line_edit.setPlaceholderText(_translate("MainWindow", "54.756", None))
        self.c2v_quad2_strength_label.setText(_translate("MainWindow", "QUAD2 Strength (k)", None))
        self.c2v_quad2_strength_line_edit.setPlaceholderText(_translate("MainWindow", "-46.099", None))
        self.c2v_quad3_strength_label.setText(_translate("MainWindow", "QUAD3 Strength (k)", None))
        self.c2v_quad3_strength_line_edit.setPlaceholderText(_translate("MainWindow", "55.974", None))
        self.c2v_quad1_strength_label.setText(_translate("MainWindow", "QUAD1 Strength (k)", None))
        self.label_2.setText(_translate("MainWindow", "C2V", None))
        self.directory_label.setText(_translate("MainWindow", "Directory", None))
        self.runButton.setText(_translate("MainWindow", "Run ASTRA", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionImport_YAML.setText(_translate("MainWindow", "Import YAML", None))
        self.actionExport_YAML.setText(_translate("MainWindow", "Export YAML", None))
